name: mood_diary
description: A new Flutter project that tracks your daily mood.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # SharedPreferencesの代わりにメモリ内で状態管理

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  shared_preferences: ^2.2.0  # データの永続化
  intl: ^0.18.0               # 日付フォーマット

flutter:
  uses-material-design: true